#! /bin/sh

killall polybar -q

sxhkd &
polybar top &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 	 21

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-center ~/Downloads/Arch-Linux-2.jpg

#Border colors
bspc config normal_border_color "#282a31"
bspc config focused_border_color "#8b9497"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

